version: '3'
services:
  mysql-master:
    container_name: 'mysql-master'
    image: 'mysql:5.6'
    ports:
      - '3306:3306'
    volumes:
      - './mysql-master/my.cnf:/etc/mysql/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: 'XGQRyJ3jLGumnGGkWsALWozv'
  mysql-slave-0:
    container_name: 'mysql-slave-0'
    image: 'mysql:5.6'
    depends_on:
      - 'mysql-master'
    ports:
      - '3307:3306'
    volumes:
      - './mysql-slave-0/my.cnf:/etc/mysql/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: 'XGQRyJ3jLGumnGGkWsALWozv'
  mysql-slave-1:
    container_name: 'mysql-slave-1'
    image: 'mysql:5.6'
    depends_on:
      - 'mysql-master'
    ports:
      - '3308:3306'
    volumes:
      - './mysql-slave-1/my.cnf:/etc/mysql/my.cnf'
    environment:
      MYSQL_ROOT_PASSWORD: 'XGQRyJ3jLGumnGGkWsALWozv'
