version: '3'
services:
  ss-server:
    container_name: 'ss-server'
    build: './ss-server'
    image: 'ss-server'
    ports:
      - '8388:8388'
    volumes:
      - './ss-server/conf/ss-server.json:/etc/shadowsocks/ss-server.json:ro'
